Escape additional json illegal chars
bitmovin-engineering/action-junit-report pull request #3
Opened 2023-01-03 13:16 UTC by zigavehovec

This PR adds additional escapes for chars that are illegal in json.

2023-01-03 14:28 UTC, krocard commented on src/failedTestsReport.ts
> +    .replace(/\v/g, '\\v')
Could we not use `JSON.stringify` instead? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify

2023-01-03 14:29 UTC, krocard requested changes
Could we not use `JSON.stringify` instead? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify

2023-01-04 09:46 UTC, zigavehovec commented
> Could we not use `JSON.stringify` instead? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify

Very good idea. 
I was thrown off by this function when I first evaluated it because it adds double quote marks to the string (json notation). 
But it's probably still a better idea to use it and remove first and last char form the output.

2023-01-04 14:25 UTC, krocard approved these changes

2023-01-04 14:29 UTC, krocard approved these changes

2023-01-04 17:19 UTC, merged